export const URL_LOGIN = "http://localhost:5000/api/login"
export const URL_SIGNUP = "http://localhost:5000/api/signup"
export const URL_INVOICES = "http://localhost:5000/api/user/invoices"
export const URL_GET_INVOICES = "http://localhost:5000/api/invoices/user"
export const URL_SOCKETIO = "ws://localhost:5000/ws"